### ISSUE TITLE
uk_os_OSGM15_GB.tif Max error

### ISSUE THREAD

**Issue by SilverSloth** [OSGeo/PROJ-data#40]
Reason for large max error in uk_os_OSGM15_GB.tif Needs checking. Possible typo error in readme file, 0.002m perhaps instead of 0.02m. Thumbs up for creating it.

**Comment by rouault** [comment]
Can you expand a bit more the text ? I'm not clear what issue you are reporting. See https://github.com/OSGeo/PROJ-data/pull/25#issuecomment-638119860 for more details about creation of this grid

**Comment by SilverSloth** [comment]
Yes, this confirms it’s a minor error in the readme file for the grid. Max error is written as 0.02m but should be 0.002m. 

Will get around to trying the grid one day.

**Comment by rouault** [comment]
@and-marsh  uk_os_README.txt mentions: "will agree on average to better than 0.1m (0.1m rmse, 68%
probability).". It seems that this is pessimistic compared to your findings at https://github.com/OSGeo/PROJ-data/pull/25#issuecomment-638119860 .

**Comment by and-marsh** [comment]
@SilverSloth @rouault yes, that's a mistake in the README, of course max error should be 0.002m. But that's an error of reprojection not transformation. I checked that orthometric height obtained by reprojected geoid file matches with results of original transformation, provided by Ordnance Survey. So that RMSE must be taken into account along with the stated error of the original transformation. 

In accordance to the EPSG registry coordinate transformation ETRS89 to ODN height (1), code: EPSG::10021 has accuracy 0.02m. So, using reprojected geoid additional error 0.002m can appear.

**Comment by and-marsh** [comment]
I can fix the README and try to explain more clearly the reason of additional error appearing if necessary.

**Comment by rouault** [comment]
> I can fix the README and try to explain more clearly the reason of additional error appearing if necessary.

yes, that would be helpful if you could separate the accuracy of the official transformation as provided by Ordnance Survey, from the addition error added by using the PROJ grid.
